#Table Printing (Interactive Version) by Cameron Knapp [243]
def printTable(tableData):                                 # Define a function that prints a table...
    colWidths = [0] * len(tableData)                       # Create a list of zeros, one per column, to track max width...
    for i in range(len(tableData)):                        # Loop through each column index...
        for item in tableData[i]:                          # Loop through each item in this column...
            if len(item) > colWidths[i]:                   # If item length is greater than current max width...
                colWidths[i] = len(item)                   # Update column width with this item’s length...

    numRows = max(len(col) for col in tableData)           # Find the number of rows = longest column length...
    for row in range(numRows):                             # Loop through each row index...
        for col in range(len(tableData)):                  # Loop through each column index...
            if row < len(tableData[col]):                  # Check if this column has an item for this row...
                text = tableData[col][row]                 # If yes, assign that item to variable `text`...
            else:
                text = ""                                  # If no, use an empty string as filler
            print(text.rjust(colWidths[col]), end=' ')     # Print item right-justified, stay on same line...
        print()                                            # After all columns in this row, move to new line...

tableData = []                                             # Start with an empty list for all columns...

while True:                                                # Keep looping until user decides to stop...
    print("Start entering items for a new column.")
    column = []                                            # Temporary list for the current column...
    while True:                                            # Keep asking until user finishes this column...
        item = input("Enter an item (or press Enter if column is done): ")
        if item == "":                                     # If input is blank, stop this column...
            break
        column.append(item)                                # Otherwise, add item to the column...

    if len(column) == 0:                                   # If no items were entered in this column...
        print("Empty column discarded.")                   # Discard the empty column...
    else:
        tableData.append(column)                           # Otherwise, add completed column to tableData...

    while True:                                            # Validation loop for yes/no input...
        more = input("Would you like to add another column? (yes/no): ").lower()
        if more in ("yes", "no"):                          # Only accept yes or no...
            break                                          # Exit validation loop if valid...
        else:
            print("Invalid response. Please type 'yes' or 'no'.")

    if more == "no":                                       # If user said no, stop adding columns...
        break

if len(tableData) == 0:                                    # If no data was entered at all...
    print("No table created — no data entered.")           # Print message instead of table...
else:
    print("\nHere is your formatted table:\n")             # Print header before showing the table...
    printTable(tableData)                                  # Call the function to print formatted table!

