#Table Printing (Non-Interactive Version) by Cameron Knapp [243]
def printTable(tableData):                                # Define the function with a list of lists...
    colWidths = [0] * len(tableData)                      # Create list of 0s, one for each column...

    # Find the longest string in each column...
    for i in range(len(tableData)):                       # Loop through each column...
        for item in tableData[i]:                         # Loop through each string in the column...
            if len(item) > colWidths[i]:                  # If string is longer than current maximum length...
                colWidths[i] = len(item)                  # Update column width to accomodate this length...

    # Print the table row by row...
    numRows = len(tableData[0])                           # Number of rows = length of first column...
    for row in range(numRows):                            # Loop through each row...
        for col in range(len(tableData)):                 # Loop through each column...
            print(tableData[col][row].rjust(colWidths[col]), end=' ')
            # Right-justify each item based on column width
        print()                                           # Move to next line after each row...


# Example data from instructions...
tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose']]

# Print the table with the data above!
printTable(tableData)
